#!/usr/bin/env python3
"""
Generate per-provider bats test files from src/providers.json.

Usage:
    python3 tests/generate_provider_tests.py

Output:
    tests/e2e/generated/sync-{provider}.bats  (one file per provider)

Each generated file contains 9 tests per provider:
  1. sync writes config to the correct path
  2. output is valid JSON (or TOML for codex)
  3. correct MCP key is used (mcpServers / mcp / mcp_servers)
  4. stdio server: command/args schema is correct
  5. stdio server: env key name is correct
  6. http server: URL field name is correct
  7. secret references are resolved
  8. path variables ({{paths.code}}) are expanded
  9. skills are symlinked (or reported as native)
"""

import json
import os
import sys
import textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(HERE)
PROVIDERS_JSON = os.path.join(REPO_ROOT, "src", "providers.json")
OUTPUT_DIR = os.path.join(HERE, "e2e", "generated")


def load_providers():
    with open(PROVIDERS_JSON) as f:
        data = json.load(f)
    return {
        k: v for k, v in data.items() if not k.startswith("$") and not k.startswith("_")
    }


def merged_array(provider_cfg):
    stdio = provider_cfg["configStructure"].get("stdioPropertyMapping", {})
    return stdio.get("argsProperty") == stdio.get("commandProperty")


def is_cli_provider(provider_cfg):
    return provider_cfg.get("configFormat") == "cli"


def is_toml_provider(provider_cfg):
    return provider_cfg.get("configFormat") == "toml"


def skills_native(provider_cfg):
    return provider_cfg.get("skills", {}).get("method") == "native"


def generate_bats(pid, p):
    cfg = p["configStructure"]
    mcp_key = cfg["serversPropertyName"]
    http_map = cfg.get("httpPropertyMapping", {})
    stdio_map = cfg.get("stdioPropertyMapping", {})
    url_prop = http_map.get("urlProperty", "url")
    env_prop = stdio_map.get("envProperty", "env")
    cmd_prop = stdio_map.get("commandProperty", "command")
    args_prop = stdio_map.get("argsProperty", "args")
    is_merged = merged_array(p)
    is_cli = is_cli_provider(p)
    is_toml = is_toml_provider(p)
    is_native_skills = skills_native(p)

    detect_cmd = p.get("detectCommand", pid)
    display = p.get("displayName", pid)

    config_path_raw = p.get("configPath", {})
    if isinstance(config_path_raw, dict):
        config_path_unix = config_path_raw.get(
            "darwin", config_path_raw.get("linux", "")
        )
    else:
        config_path_unix = config_path_raw
    config_path_unix = config_path_unix.replace("$HOME", "$HOME")

    skills_path_raw = p.get("skills", {}).get("path", {})
    if isinstance(skills_path_raw, dict):
        skills_path_unix = skills_path_raw.get(
            "darwin", skills_path_raw.get("linux", "")
        )
    else:
        skills_path_unix = skills_path_raw
    skills_path_unix = skills_path_unix.replace("$HOME", "$HOME")

    lines = []

    def emit(*args):
        lines.append(" ".join(str(a) for a in args))

    def ln(s=""):
        lines.append(s)

    header = textwrap.dedent(f"""\
        #!/usr/bin/env bats
        # Auto-generated by tests/generate_provider_tests.py — DO NOT EDIT
        # Provider: {display} ({pid})

        load '../../test_helper'

        RESOLVER="{REPO_ROOT}/src/lib/config_resolver.py"

        setup() {{
          setup_test_env
          agentctl init
          mock_secrets_backend
          set_test_secret "GITHUB_TOKEN" "test_gh_token_value"
          agentctl add-server stdio-srv npx -y @example/mcp-server
          python3 << 'PYEOF'
        import json, os
        p = os.environ['AGENTS_DIR']
        with open(f'{{p}}/mcp-config.json') as f:
            cfg = json.load(f)
        cfg['stdio-srv']['env'] = {{'GITHUB_TOKEN': 'secret:GITHUB_TOKEN'}}
        cfg['http-srv'] = {{
            'transport': 'http',
            'url': 'https://example.com/mcp',
            'headers': {{'Authorization': 'Bearer secret:GITHUB_TOKEN'}}
        }}
        with open(f'{{p}}/mcp-config.json', 'w') as f:
            json.dump(cfg, f, indent=2)
        PYEOF
          agentctl config set paths.code "/tmp/testcode"
        }}

        teardown() {{
          teardown_test_env
        }}

        _resolver() {{
          python3 "$RESOLVER" \\
            --mcp-config  "$AGENTS_DIR/mcp-config.json" \\
            --user-config "$AGENTS_DIR/config.json" \\
            --secrets-sh  "{REPO_ROOT}/src/lib/secrets.sh" \\
            "$@"
        }}
    """)
    lines.append(header.rstrip())
    ln()

    if is_cli:
        ln(f'@test "{pid}: sync via CLI requires {detect_cmd} binary" {{')
        ln(f"  skip_if_missing {detect_cmd}")
        ln(f"  run _resolver --action sync --provider {pid}")
        ln(f'  [ "$status" -eq 0 ]')
        ln("}")
        ln()
        for i in range(2, 10):
            ln(
                f'@test "{pid}: test {i} (CLI provider — config via {detect_cmd} mcp add)" {{'
            )
            ln(f'  skip "Claude manages config via CLI, not a config file"')
            ln("}")
            ln()
        return "\n".join(lines)

    ln(f'@test "{pid}: sync writes config to correct path" {{')
    ln(f"  skip_if_missing {detect_cmd}")
    ln(f'  local cfg_path="{config_path_unix}"')
    ln(f'  mkdir -p "$(dirname "$cfg_path")"')
    ln(f"  run _resolver --action sync --provider {pid}")
    ln(f'  [ "$status" -eq 0 ]')
    ln(f'  [ -f "$cfg_path" ]')
    ln("}")
    ln()

    if is_toml:
        ln(f'@test "{pid}: config file is valid TOML-style text" {{')
        ln(f"  skip_if_missing {detect_cmd}")
        ln(f'  local cfg_path="{config_path_unix}"')
        ln(f'  mkdir -p "$(dirname "$cfg_path")"')
        ln(f"  _resolver --action sync --provider {pid}")
        ln(f'  grep -q "=" "$cfg_path"')
        ln("}")
        ln()

        ln(f'@test "{pid}: correct MCP section key used ({mcp_key})" {{')
        ln(f"  skip_if_missing {detect_cmd}")
        ln(f'  local cfg_path="{config_path_unix}"')
        ln(f'  mkdir -p "$(dirname "$cfg_path")"')
        ln(f"  _resolver --action sync --provider {pid}")
        ln(f'  grep -q "\\[{mcp_key}\\." "$cfg_path"')
        ln("}")
        ln()

        ln(f'@test "{pid}: stdio server command is present" {{')
        ln(f"  skip_if_missing {detect_cmd}")
        ln(f'  local cfg_path="{config_path_unix}"')
        ln(f'  mkdir -p "$(dirname "$cfg_path")"')
        ln(f"  _resolver --action sync --provider {pid}")
        ln(f'  grep -q "command" "$cfg_path"')
        ln("}")
        ln()

        ln(f'@test "{pid}: stdio server env key is correct ({env_prop})" {{')
        ln(f"  skip_if_missing {detect_cmd}")
        ln(f'  local cfg_path="{config_path_unix}"')
        ln(f'  mkdir -p "$(dirname "$cfg_path")"')
        ln(f"  _resolver --action sync --provider {pid}")
        ln(f'  grep -q "{env_prop}" "$cfg_path"')
        ln("}")
        ln()

        ln(f'@test "{pid}: http server URL field is correct ({url_prop})" {{')
        ln(f"  skip_if_missing {detect_cmd}")
        ln(f'  local cfg_path="{config_path_unix}"')
        ln(f'  mkdir -p "$(dirname "$cfg_path")"')
        ln(f"  _resolver --action sync --provider {pid}")
        ln(f'  grep -q "example.com" "$cfg_path"')
        ln("}")
        ln()

        ln(f'@test "{pid}: secret references are resolved at sync time" {{')
        ln(f"  skip_if_missing {detect_cmd}")
        ln(f'  local cfg_path="{config_path_unix}"')
        ln(f'  mkdir -p "$(dirname "$cfg_path")"')
        ln(f"  _resolver --action sync --provider {pid}")
        ln(f'  run grep "secret:" "$cfg_path"')
        ln(f'  [ "$status" -ne 0 ]')
        ln("}")
        ln()

        ln(f'@test "{pid}: path variables are expanded" {{')
        ln(f"  skip_if_missing {detect_cmd}")
        ln(f'  local cfg_path="{config_path_unix}"')
        ln(f'  mkdir -p "$(dirname "$cfg_path")"')
        ln(f"  _resolver --action sync --provider {pid}")
        ln(f'  run grep "paths\\." "$cfg_path"')
        ln(f'  [ "$status" -ne 0 ]')
        ln("}")
        ln()

    else:
        ln(f'@test "{pid}: config file is valid JSON" {{')
        ln(f"  skip_if_missing {detect_cmd}")
        ln(f'  local cfg_path="{config_path_unix}"')
        ln(f'  mkdir -p "$(dirname "$cfg_path")"')
        ln(f"  _resolver --action sync --provider {pid}")
        ln(f"  python3 -c \"import json; json.load(open('$cfg_path'))\"")
        ln("}")
        ln()

        ln(f'@test "{pid}: correct MCP key used ({mcp_key})" {{')
        ln(f"  skip_if_missing {detect_cmd}")
        ln(f'  local cfg_path="{config_path_unix}"')
        ln(f'  mkdir -p "$(dirname "$cfg_path")"')
        ln(f"  _resolver --action sync --provider {pid}")
        ln(
            f"  python3 -c \"import json; d=json.load(open('$cfg_path')); assert '{mcp_key}' in d\""
        )
        ln("}")
        ln()

        if is_merged:
            ln(f'@test "{pid}: stdio server uses merged command array" {{')
            ln(f"  skip_if_missing {detect_cmd}")
            ln(f'  local cfg_path="{config_path_unix}"')
            ln(f'  mkdir -p "$(dirname "$cfg_path")"')
            ln(f"  _resolver --action sync --provider {pid}")
            ln(f"  python3 << 'PYEOF'")
            ln(f"import json, os")
            ln(
                f'cfg = json.load(open(os.environ["HOME"] + "/{config_path_unix.lstrip("$HOME/")}"))'
                if "$HOME" in config_path_unix
                else f'cfg = json.load(open("{config_path_unix}"))'
            )
            ln(f'srv = cfg["{mcp_key}"]["stdio-srv"]')
            ln(
                f'assert isinstance(srv["{cmd_prop}"], list), f"expected list, got {{type(srv[\'{cmd_prop}\'])}}"'
            )
            ln(f"PYEOF")
            ln("}")
        else:
            ln(f'@test "{pid}: stdio server has separate command and args fields" {{')
            ln(f"  skip_if_missing {detect_cmd}")
            ln(f'  local cfg_path="{config_path_unix}"')
            ln(f'  mkdir -p "$(dirname "$cfg_path")"')
            ln(f"  _resolver --action sync --provider {pid}")
            ln(
                f"  python3 -c \"import json; s=json.load(open('$cfg_path'))['{mcp_key}']['stdio-srv']; assert '{cmd_prop}' in s and '{args_prop}' in s\""
            )
            ln("}")
        ln()

        ln(f'@test "{pid}: stdio server env key is {env_prop}" {{')
        ln(f"  skip_if_missing {detect_cmd}")
        ln(f'  local cfg_path="{config_path_unix}"')
        ln(f'  mkdir -p "$(dirname "$cfg_path")"')
        ln(f"  _resolver --action sync --provider {pid}")
        ln(
            f"  python3 -c \"import json; s=json.load(open('$cfg_path'))['{mcp_key}']['stdio-srv']; assert '{env_prop}' in s\""
        )
        ln("}")
        ln()

        ln(f'@test "{pid}: http server URL field is {url_prop}" {{')
        ln(f"  skip_if_missing {detect_cmd}")
        ln(f'  local cfg_path="{config_path_unix}"')
        ln(f'  mkdir -p "$(dirname "$cfg_path")"')
        ln(f"  _resolver --action sync --provider {pid}")
        ln(
            f"  python3 -c \"import json; s=json.load(open('$cfg_path'))['{mcp_key}']['http-srv']; assert '{url_prop}' in s\""
        )
        ln("}")
        ln()

        ln(
            f'@test "{pid}: secret references are resolved (no literal secret: in config)" {{'
        )
        ln(f"  skip_if_missing {detect_cmd}")
        ln(f'  local cfg_path="{config_path_unix}"')
        ln(f'  mkdir -p "$(dirname "$cfg_path")"')
        ln(f"  _resolver --action sync --provider {pid}")
        ln(f'  run grep "secret:" "$cfg_path"')
        ln(f'  [ "$status" -ne 0 ]')
        ln("}")
        ln()

        ln(f'@test "{pid}: path variables expanded (no {{{{paths.X}}}} in config)" {{')
        ln(f"  skip_if_missing {detect_cmd}")
        ln(f'  local cfg_path="{config_path_unix}"')
        ln(f'  mkdir -p "$(dirname "$cfg_path")"')
        ln(f"  _resolver --action sync --provider {pid}")
        ln(f'  run grep "paths\\." "$cfg_path"')
        ln(f'  [ "$status" -ne 0 ]')
        ln("}")
        ln()

    if is_native_skills:
        ln(f'@test "{pid}: skills are native (reads ~/.agents/skills directly)" {{')
        ln(f'  create_test_skill "$AGENTS_DIR/skills/gen-skill" "gen-skill"')
        ln(f"  run _resolver --action sync-skills \\")
        ln(f'    --skills-dir "$AGENTS_DIR/skills" \\')
        ln(f'    --skills-target "$AGENTS_DIR/skills" \\')
        ln(f"    --provider {pid}")
        ln(f'  [ "$status" -eq 0 ]')
        ln("}")
    else:
        ln(f'@test "{pid}: skills are symlinked to provider skills dir" {{')
        ln(f"  skip_if_missing {detect_cmd}")
        ln(f'  create_test_skill "$AGENTS_DIR/skills/gen-skill" "gen-skill"')
        ln(f'  local target="$(mktemp -d)"')
        ln(f"  run _resolver --action sync-skills \\")
        ln(f'    --skills-dir "$AGENTS_DIR/skills" \\')
        ln(f'    --skills-target "$target" \\')
        ln(f"    --provider {pid}")
        ln(f'  [ "$status" -eq 0 ]')
        ln(f'  [ -L "$target/gen-skill" ]')
        ln(f'  rm -rf "$target"')
        ln("}")
    ln()

    return "\n".join(lines)


def main():
    providers = load_providers()
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    generated = []
    for pid, p in providers.items():
        content = generate_bats(pid, p)
        out_path = os.path.join(OUTPUT_DIR, f"sync-{pid}.bats")
        with open(out_path, "w") as f:
            f.write(content + "\n")
        os.chmod(out_path, 0o755)
        generated.append(out_path)
        print(f"  wrote {out_path}")

    print(f"\nGenerated {len(generated)} test files in {OUTPUT_DIR}/")
    print("Run with: bats tests/e2e/generated/")


if __name__ == "__main__":
    main()
